name: 'Terraform Deploy'

on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    # Definimos las variables de entorno a nivel de JOB para que todos los pasos las usen
    env:
      TF_VAR_host_project_id: "zafa-host"
      TF_VAR_project_id: "zafa-dev"

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
        service_account: ${{ secrets.GCP_SA_EMAIL }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      working-directory: ./environments/dev

    - name: Terraform Plan
      # Usamos -lock=false para evitar el error 412 del bucket
      run: terraform plan -lock=false
      working-directory: ./environments/dev
      # Si algo sale mal, que no se quede colgado 10 horas
      timeout-minutes: 10 

    - name: Terraform Apply
      # Solo se ejecuta si estamos en main
      if: github.ref == 'refs/heads/main'
      # -auto-approve para que no pida "yes" y -lock=false para el bucket
      run: terraform apply -auto-approve -lock=false
      working-directory: ./environments/dev
      timeout-minutes: 20