name: 'Terraform Deploy'

on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    # Variables de entorno globales para todo el JOB
    env:
      TF_VAR_host_project_id: "zafa-host"
      TF_VAR_project_id: "zafa-dev"
      # Nivel máximo de logs: TRACE (muestra cada llamada a la API de Google)
      TF_LOG: TRACE

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
        service_account: ${{ secrets.GCP_SA_EMAIL }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false # Desactivamos el wrapper para ver logs puros de consola

    - name: Terraform Init
      id: init
      run: |
        terraform init \
          -input=false \
          -lock=false
      working-directory: ./environments/dev

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan \
          -input=false \
          -lock=false \
          -no-color \
          -detailed-exitcode || exit_code=$?
      working-directory: ./environments/dev
      # Si no termina en 10 minutos, cortamos para ver el log acumulado
      timeout-minutes: 10 

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: |
        terraform apply \
          -auto-approve \
          -input=false \
          -lock=false
      working-directory: ./environments/dev
      timeout-minutes: 20